### PR TITLE
Migration from Bower

### PR DESCRIPTION
**Pull request by jonathanlking**
### Description of the change

This (when completed) addresses #159.

### Checklist:

- [ ] Added the change to the "Unreleased" section of the changelog
- [ ] Added some example of the new feature to the `README`
- [ ] Added a test for the contribution (if applicable)

**P.S.**: the above checks are not compulsory to get a change merged, so you may skip them. However, taking care of them will result in less work for the maintainers and will be much appreciated 😊

### CODE REVIEW

**Comment by jonathanlking** [comment]
This was originally intended as a command to verify that package set satisfies bower dependencies, however after speaking to @f-f I was made aware of #159. I'm going to refactor it to run on `spago init` and add the dependencies to the `spago.dhall`.

**Comment by f-f** [comment]
@jonathanlking I think we're done with the invasive changes to Bower-related code after #324, would you still like to work on this? If yes then we can rebase on #324, if not I can pick this up as it's needed for 1.0 anyways 🙂 

Also no worries about fixing #159 here, I'd be fine merging pretty much what you have here already (except we should remove the command line stuff) and tackling the rest in a later PR - the policy is that I'm fine even merging code that is not used anywhere yet if it's needed as a stepping stone for other things

**Comment by jonathanlking** [comment]
@f-f Thanks for letting me know 😄
I think your suggestion about removing the command line interface an merging sounds good. I still think there is some value in this check being "continuously" run, rather than just at conversion - given that we need to keep a `bower.json` file around for Pursuit.
I intend to rebase and remove the command line interface. I had forgotten about local packages when implementing this, so they are currently unsupported.

**Comment by f-f** [comment]
@jonathanlking thank you! A few notes:
- note that when using `spago bump-version` (implemented, shipping in next version) and `spago publish` (to be implemented soon) the `bower.json` is generated from the `spago.dhall`, and not viceversa. I.e. this conversion will need to happen only when porting a bower package to Spago, and after that Spago will take care of keeping bower file consistent over time
- no worries about local packages, we'll fix them in the process of taking this code into use (also there's #301 that shuffles the local packages a bit, so it's ok to not worry about them here)

**Comment by f-f** [comment]
@jonathanlking I think if you merge https://github.com/jonathanlking/spago/pull/1 then it will pass CI

**Comment by jonathanlking** [comment]
@f-f thanks 🙂 - I've merged it and fixed the warnings.

**Pull request merged**
