### PR TITLE
Adds logging flags

### PR DESCRIPTION
**Pull request by matthew-hilty**
### Description of the change

Adds `--quiet` (`-q`) flag that suppresses all Spago logging.
Adds `--no-color` (`-C`) flag that disables ANSI color escape sequences.

### Checklist:

- [ ] Added the change to the "Unreleased" section of the changelog
- [ ] Added some example of the new feature to the `README`
- [ ] Added a test for the contribution (if applicable)

**P.S.**: the above checks are not compulsory to get a change merged, so you may skip them. However, taking care of them will result in less work for the maintainers and will be much appreciated 😊

### CODE REVIEW

**Comment by f-f** [comment]
@matthew-hilty thank you for doing this! :slightly_smiling_face:

**Comment by matthew-hilty** [comment]
@f-f , you're very welcome. Thank you too!

**Comment by shamansir** [comment]
Seems having some output when using `spago` as a builder for [VSCode extension](https://github.com/nwolverson/vscode-ide-purescript), breaks it from building, being exact: `spago build --purs-args --json-errors` gives as an output (for version 0.13.1):

```
[info] Installation complete.
{"warnings":[],"errors":[]}
[info] Build succeeded.
```

So this is the important fix, please publish it as a version.

**Comment by f-f** [comment]
@shamansir I just cut [a new release](https://github.com/purescript/spago/releases/tag/0.14.0), it should be up on npm shortly

**Comment by shamansir** [comment]
@f-f Awesome, thank you a lot!

**Comment by f-f** [comment]
You're welcome :slightly_smiling_face:

**Comment by shamansir** [comment]
Seems spago `v0.14.0` still outputs _Compiling ..._ messages, even with `--quiet` flag.

I am running the command `spago --quiet build --purs-args --json-errors` in my project and there are lines of:

```
Compiling Data.List
Compiling Data.Maybe
. . . <hundreds of lines omitted>
{"warnings":[{"moduleName":...<here goes JSON>...}
```

Which could break the VSCode plugin parser which still expects only to get JSON.

Could be related to #540

**Comment by matthew-hilty** [comment]
Hi, @shamansir.

I think the "Compiling ..." statements are ```ProgressMessage```s emitted by the purs compiler itself, not by spago. And, unfortunately, users have no option of silencing progress messages.

However, as of purs v0.13.6 and at least until purescript issue 3672 is resolved, there is a potential workaround. Since purs emits progress messages onto stdout and json-errors onto stderr, to ignore the "Compiling ..." statements while retaining json-errors, you need only redirect a couple of file descriptors: 

```bash
spago --quiet build --purs-args --json-errors 2>&1 1>/dev/null
```

**Comment by f-f** [comment]
Since that output is coming straight from `purs`, something we could do in this case would be to not output that at all when `--quiet` is passed. Would that work?

**Comment by matthew-hilty** [comment]
I don't think there's a command-line flag or any other hook accessible to Spago code for silencing the "Compiling ..." statements, although it seems like a good feature for `purs` developers to include. However, until that point, there doesn't seem to be any officially supported way for `purs` clients (either Spago itself or Spago's end users) to filter out progress messages.

As far as I can tell, there are only two possible solutions, both kludges:
1. Spago can pattern match on all of `purs`'s output and strip progress messages from `stdout`. (However, I wouldn't recommend this; my guess is that this tactic would be rather error prone.)
2. Command-line users like @shamansir can redirect `stdout` and its progress messages to some out-of-the-way file descriptor.

**Comment by matthew-hilty** [comment]
Unless, do you mean, have Spago suppress the compiler's `stdout`-output entirely?

That would work, but it seems a tad heavy-handed. Most PureScript developers, I expect, have high technical competence and can probably redirect output streams for themselves. Having Spago do it for them might make for a better user-interface, but eventually, `purs` is going to change its `stdout`/`stderr` model anyway, so it might not be worth the bother.

**Pull request merged**
