### PR TITLE
feat: nix -> add support

### PR DESCRIPTION
**Pull request by srghma**
### Description of the change

adds nix support

Done as part of https://github.com/spacchetti/spago/issues/220

### Checklist:

- [ ] Added the change to the "Unreleased" section of the changelog
- [ ] Added some example of the new feature to the `README`
- [ ] Added a test for the contribution (if applicable)

**P.S.**: the above checks are not compulsory to get a change merged, so you may skip them. However, taking care of them will result in less work for the maintainers and will be much appreciated 😊

### CODE REVIEW

**Comment by f-f** [comment]
Hi @srghma, thanks for the PR!

Unfortunately I would not like to merge this, because:
- if you are looking just for a way to install `spago` under NixOS, you can use [easy-purescript-nix](https://github.com/justinwoo/easy-purescript-nix/blob/master/spago.nix)
- if this is about adding a dev setup for Nix, I'd say I'm not interested in supporting anything else than `stack`, as documented in the [contributing file](https://github.com/spacchetti/spago/blob/master/CONTRIBUTING.md#developing-spago) - the reason for this is that is going to be hard for me to onboard new contributors if I have to support dev setups that I don't use

**Comment by srghma** [comment]
@f-f

1) easy-purescript-nixs use already built binaries from https://github.com/purescript/psc-package/releases/download

this pr allows to use custom branches

**Comment by f-f** [comment]
> easy-purescript-nixs use already built binaries

Yes, that's the whole point of it. As said above, I'm not interested in a setup to build binaries from Nix

(As an aside, I'm on NixOS and `stack install` works well for me)

**Comment by srghma** [comment]
@f-f anyway, please dont close this pr, it may be handy for others

**Comment by f-f** [comment]
@srghma: the PR is not really needed for others to discover this - GitHub search works on closed issues/PRs too, and unless you delete the branch people will be able to use it

The problem with leaving open a PR that we don't want to merge is that me (or other contributors) might accidentally merge it, which is easy since CI passed - so I'll close this

**Pull request closed without merging**
