### PR TITLE
Replace bundle-app by bundle and bundle-module by make-module in README.

### PR DESCRIPTION
**Pull request by epost**
### Description of the change

TODO

### PR checklist:

- [ ] Updated the version number [in `package.yaml`](https://github.com/spacchetti/spago/blob/master/package.yaml#L2) according to SemVer (`0.x.y.z`, `x` bumps on breaking changes, `y` on additions, `z` on patches)
- [ ] Added the change to the "Unreleased" section of the changelog
- [ ] Added some example of the new feature to the `README`
- [ ] Added a test for the contribution (if applicable)

**P.S.**: the above checks are not compulsory to get a change merged, so you may skip them. However, taking care of them will result in less work for the maintainers and will be much appreciated 😊

### CODE REVIEW

**Comment by f-f** [comment]
Hi @epost! I think there's a misunderstanding here, the README is correctly using the new commands `bundle-module` and `bundle-app`, which are due to be released in `0.8`, see the relevant issue: https://github.com/spacchetti/spago/issues/147

The docs for the current release are here: https://github.com/spacchetti/spago/tree/0.7.7.0

So I'll close this and release as soon as possible (some documentation is still missing)

**Comment by epost** [comment]
@f-f Oh, sorry about that! Thanks for the pointer. Glad to hear it though; the new names are nicer. :)

**Comment by f-f** [comment]
You're welcome! 🙂

**Comment by f-f** [comment]
Just released [0.8.0](https://github.com/spacchetti/spago/releases/tag/0.8.0.0)

**Comment by epost** [comment]
Awesome! Thanks for the heads-up!

**Pull request closed without merging**
