### PR TITLE
Fix #50: include src while building tests

### LINKED ISSUE #50: `test` command doesn't work correctly
When I run `test` command, I end up with a bunch of `Module Foo.Bar was not found` errors. It just doesn't see modules in `src` folder. So I guess the answer to [this](https://github.com/spacchetti/spago/blob/master/app/Spago.hs#L253) question is "yes" :)

### PR DESCRIPTION
**Pull request by f-f**
@starper could you try if this fixes the issue?

### CODE REVIEW

**Comment by justinwoo** [comment]
Test project test should be added

**Comment by f-f** [comment]
@justinwoo happens [here](https://github.com/spacchetti/spago/blob/master/test/spago-test.py#L44)

**Comment by justinwoo** [comment]
The tests haven't been updated? They should pull in the Main module to ensure that this behaves as expected.

**Comment by starper** [comment]
@f-f It does. Thanks.

**Comment by justinwoo** [comment]
Good to merge? @f-f

**Comment by f-f** [comment]
@justinwoo I have a commit to fix the tests, I’ll push it and cut a release later today

**Pull request merged**
