### PR TITLE
Stop reformatting the config file at every run

### LINKED ISSUE #300: Is it possible to turn off autoformatting?
It looks like every time `spago` runs, it reformats the Dhall file. Is there a way to tell `spago` not to format the files when it runs?

### PR DESCRIPTION
**Pull request by f-f**
Fix #300 

This implements the fix described in https://github.com/spacchetti/spago/issues/300#issuecomment-515676453: we remove the `--no-config-format` flag and Spago will not reformat the config file unless it's needed, removing the need for the flag

cc @joneshf @liamgoodacre @aniketd: since there is some noise in the PR, the actual fix for this is basically [these lines](https://github.com/spacchetti/spago/pull/339/files#diff-47b561d66d3fdc8da263081ea4048920R250-R253)

### CODE REVIEW

**Comment by f-f** [comment]
Also cc @aniketd: the fix for this is basically [these lines](https://github.com/spacchetti/spago/pull/339/files#diff-47b561d66d3fdc8da263081ea4048920R250-R253)

**Comment by joneshf** [comment]
Thanks for keeping me in the loop!

**Comment by f-f** [comment]
You're welcome 🙂

**Comment by aniketd** [comment]
Thanks @f-f !

**Pull request merged**
