### PR TITLE
Add option to pass arguments to node on test/run (#267)

### LINKED ISSUE #267: spago run -- needs to pass through args to node, or have some mechanism to do so
Main.js

```js
exports.argv = process.argv;
```

Main.purs

```purs
module Main where

import Prelude

import Effect (Effect)
import Effect.Aff as Aff
import Effect.Class.Console (logShow)

foreign import argv :: Array String

main :: Effect Unit
main = Aff.launchAff_ do
  logShow argv
```

actual:

```
$ spago run -- afwaefwaefo
Installation complete.
purs compile: No files found using pattern: afwaefwaefo
Build succeeded.
["my/bin/node"]
```

expected:

```
$ node -e "require('./output/Main').main()" 12313 owijewejf
["my/bin/node","12313","owijewejf"]
```

### PR DESCRIPTION
**Pull request by miangraham**
### Description of the change

First pass at --node-args (fix #267)

```bash
$ spago run
Installation complete.
Build succeeded.
["/usr/bin/node"]
$ spago run -n "foo bar"
Installation complete.
Build succeeded.
["/usr/bin/node","foo","bar"]
```

### Checklist:

- [x] Added the change to the "Unreleased" section of the changelog
- [x] Added some example of the new feature to the `README`
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by f-f** [comment]
Looks great, thank you! 👏

**Comment by paluh** [comment]
I want to ask a question about this feature. Currently `spago` executes a javascript expression in `run` and `test`. This strategy changes the behavior of option passing when we compare it to directly running bundle:

```shell
$ node output/bundle.js --help
```
passes three values: `[PATH_TO_NODE, PATH_TO_SCRIPT, "--help"]`

```shell
$ spago run --node-args --help
```
passes option directly to node and not to the purescript module. This is how node processes arguments with `-e` option.

```shell
$ spago run --node-args "-- --help"
```
passes two values `[PATH_TO_NODE, "--help"]`

Libraries like `purescript-optparse` [here](https://github.com/f-o-a-m/purescript-optparse/blob/master/src/Options/Applicative/Extra.purs#L55) or `purescript-aptlicative` [here](https://github.com/Thimoteus/purescript-optlicative/blob/master/src/Node/Optlicative/Internal.purs#L180) assume the first two arguments to be node path and script name. I think that we should think about consistent solution command arguments passing as this can be really important during testing or even development.

What do you think Guys?

**Comment by f-f** [comment]
@paluh if I read your comment correctly this should be fixed in master (went in with #297), so it will ship with the next release

**Comment by paluh** [comment]
Yeah! Thanks!

**Comment by f-f** [comment]
You're welcome 🙂

**Pull request merged**
